#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get the current branch name
branch=$(git rev-parse --abbrev-ref HEAD)

# Check if the current branch is "main"
if [ "$branch" = "main" ]; then
  # Run the generateVersion.js script to update version no
  version=$(npm --no-git-tag-version version patch)
  git add ./package* && git commit -m "build: update version $version"
fi
