name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - "openspec/**"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "openspec/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci
      - run: npm run build-prod

  test:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Retrieve Git history, needed to verify commits
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci

      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Linter
        run: npm run lint

      - name: Type checking
        run: npm run check-types

      - name: Run unit tests
        run: npm run test

      - name: Install Playwright browser for test-storybook
        run: npx playwright install --with-deps chromium

      - name: Run storybook tests
        run: npm run test-storybook:ci
